#!/bin/sh

__dirname=$(pwd)

export PATH=${__dirname}/node:${PATH}

echo $PATH

command=$1
if [ -z $command ]; then
	echo -e "available commands$(tput sgr0):"
	ls node_modules/.bin
	exit 0
fi
shift

case ${command} in
    npm)
        ./node/npm "$@" ;;
    gulp)
        ./node/node "node_modules/gulp/bin/gulp.js" "$@" ;;
    node)
        ./node/node "$@" ;;
    *)
        echo "Error: \"${COMMAND}\" not implemented"
esac
