export const FETCH_LIGHTS_DATA_REQUEST = 'FETCH_LIGHTS_DATA_REQUEST';
export const FETCH_LIGHTS_DATA_SUCCESS = 'FETCH_LIGHTS_DATA_SUCCESS';
export const FETCH_LIGHTS_DATA_FAILURE = 'FETCH_LIGHTS_DATA_FAILURE';

export const TOGGLE_LIGHT_REQUEST = 'TOGGLE_LIGHT_REQUEST';
export const TOGGLE_LIGHT_SUCCESS = 'TOGGLE_LIGHT_SUCCES';
export const TOGGLE_LIGHT_FAILURE = 'TOGGLE_LIGHT_FAILURE';

